# Workflow for updating flags in the repository
name: Update Flags

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_flags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Update Flag File
        run: |
          echo "Last updated: $(date -u)" > flag.txt
      - name: Commit and Push Flag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flag.txt
          git commit -m "Update flag on directory change" || echo "No changes to commit"
          git push
